package api

// nodeInstallScript is the installer this server hands to a new node.
//
// POSIX sh, not bash: a stripped Debian or an Alpine box on the fleet is an
// ordinary thing, and an installer that needs its own shell installed first is
// one more step in the process it exists to remove.
//
// The single verb is the server's base URL, checked against safeHost before it
// is written. Everything else is fixed, because a script assembled from request
// parameters is a script an attacker helps write.
const nodeInstallScript = `#!/bin/sh
# Install or update the Wintermute fleet agent on this host.
#
# Generated by the server it came from, which is why the address below is
# already filled in. Re-running it updates the binary in place and leaves
# /etc/wintermute/node.env alone -- that file holds this host's token and the
# choices made about this machine.
#
#   curl -fsSL -H "Authorization: Bearer $TOKEN" SERVER/api/v1/node-agent/install.sh \
#     | sudo sh -s -- --token "$TOKEN"
#
# The token is the one printed by, on the server:
#
#   wintermuted -add-client <name> -kind node
#
# That name is how this machine is identified everywhere afterwards, including
# in the "node" field of a backend declaration.
set -eu

SERVER="%s"
TOKEN=""
STORE=""
RUNTIME=""

BIN_DIR="/usr/local/bin"
BIN="$BIN_DIR/wintermute-node"
ENV_DIR="/etc/wintermute"
ENV_FILE="$ENV_DIR/node.env"
UNIT="/etc/systemd/system/wintermute-node.service"
DROPIN_DIR="/etc/systemd/system/wintermute-node.service.d"
SERVICE_USER="wintermute-node"
STATE_DIR="/var/lib/wintermute-node"

die() { echo "error: $*" >&2; exit 1; }
say() { echo "==> $*"; }

usage() {
  cat <<'USAGE'
Usage: install.sh --token <token> [options]

  --token <token>     this node's token, from:
                        wintermuted -add-client <name> -kind node
                      Required on a first install; on an update it is read from
                      the existing /etc/wintermute/node.env.
  --server <url>      override the server address baked into this script.
  --store <path>      keep model weights here, so switching a model is a local
                      file read. Adds a systemd drop-in granting write access to
                      the path when it lives outside the state directory.
  --runtime <name>    what serves models on this host: ollama or llamacpp.
                      Only meaningful with --store.

Re-run to update. The binary and the unit are replaced; node.env is not.
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --token)   [ $# -ge 2 ] || die "--token needs a value";   TOKEN="$2";   shift 2 ;;
    --server)  [ $# -ge 2 ] || die "--server needs a value";  SERVER="$2";  shift 2 ;;
    --store)   [ $# -ge 2 ] || die "--store needs a value";   STORE="$2";   shift 2 ;;
    --runtime) [ $# -ge 2 ] || die "--runtime needs a value"; RUNTIME="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; die "unknown option: $1" ;;
  esac
done

[ "$(id -u)" -eq 0 ] || die "run this as root (pipe it into 'sudo sh' rather than 'sh')"
[ "$(uname -s)" = "Linux" ] || die "the agent reads /proc, so it runs on Linux only"
command -v curl >/dev/null 2>&1 || die "curl is required"
command -v systemctl >/dev/null 2>&1 || die "systemd is required; this installs a systemd unit"

case "$(uname -m)" in
  x86_64|amd64)  ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  *) die "unsupported architecture $(uname -m); the server builds amd64 and arm64" ;;
esac

# On an update the token is already on this machine. Asking for it again would
# mean digging out a value that was shown once, months ago, to do something the
# host is already authorised for.
if [ -z "$TOKEN" ] && [ -f "$ENV_FILE" ]; then
  TOKEN="$(sed -n 's/^WINTERMUTE_TOKEN=//p' "$ENV_FILE" | tail -1)"
  [ -n "$TOKEN" ] && say "using the token already in $ENV_FILE"
fi
[ -n "$TOKEN" ] || die "--token is required for a first install"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fetch() {
  curl -fsSL --retry 3 -H "Authorization: Bearer $TOKEN" \
    "$SERVER/api/v1/node-agent/$1" -o "$2" \
    || die "could not fetch $1 from $SERVER (is the token right, and has update.sh been run there?)"
}

say "Fetching wintermute-node ($ARCH) from $SERVER"
fetch "wintermute-node.$ARCH" "$TMP/wintermute-node"

# The transfer was authenticated, so this guards against a truncated download
# rather than against a forged one. A half-written binary that installs cleanly
# and then fails to start is a bad afternoon on a machine reached over ssh.
if command -v sha256sum >/dev/null 2>&1; then
  fetch SHA256SUMS "$TMP/SHA256SUMS"
  WANT="$(awk -v f="wintermute-node.$ARCH" '$2 == f || $2 == "*" f { print $1 }' "$TMP/SHA256SUMS")"
  GOT="$(sha256sum "$TMP/wintermute-node" | cut -d" " -f1)"
  [ -n "$WANT" ] || die "SHA256SUMS on the server names no wintermute-node.$ARCH"
  [ "$WANT" = "$GOT" ] || die "checksum mismatch: the download did not arrive intact"
  say "    checksum verified"
else
  echo "    warning: sha256sum not found, skipping verification" >&2
fi

chmod 755 "$TMP/wintermute-node"
VERSION="$("$TMP/wintermute-node" -version 2>/dev/null || echo unknown)"
say "Installing $VERSION"

if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
  say "    created system user $SERVICE_USER"
fi

# Renamed into place rather than written over: the file may be executing right
# now, and writing into a running binary fails with ETXTBSY. A rename does not,
# and the running process keeps the inode it started with until it restarts.
cp "$TMP/wintermute-node" "$BIN.new"
chmod 755 "$BIN.new"
mv -f "$BIN.new" "$BIN"
say "    installed $BIN"

mkdir -p "$ENV_DIR"
# Kept beside the real one as documentation: every optional setting, with the
# reasoning, which is worth more on the host than in a repository the operator
# is not standing in.
fetch node.env.example "$ENV_DIR/node.env.example"
chmod 644 "$ENV_DIR/node.env.example"

if [ -f "$ENV_FILE" ]; then
  say "    keeping the existing $ENV_FILE"
  if [ -n "$STORE" ] || [ -n "$RUNTIME" ]; then
    echo "    note: --store and --runtime were ignored; edit $ENV_FILE to change them" >&2
  fi
else
  # Written fresh rather than by substituting into the example, so a token is
  # never fed through a regular expression.
  umask 077
  {
    echo "# Written by the Wintermute node installer. See node.env.example beside"
    echo "# this file for every other setting and what it does."
    echo "WINTERMUTE_SERVER=$SERVER"
    echo "WINTERMUTE_TOKEN=$TOKEN"
    [ -n "$STORE" ]   && echo "WINTERMUTE_NODE_STORE=$STORE"
    [ -n "$RUNTIME" ] && echo "WINTERMUTE_NODE_RUNTIME=$RUNTIME"
    true
  } > "$ENV_FILE"
  umask 022
  chown root:"$SERVICE_USER" "$ENV_FILE" 2>/dev/null || true
  chmod 640 "$ENV_FILE"
  say "    wrote $ENV_FILE"
fi

if [ -f "$UNIT" ]; then
  # Operators do edit this file -- a model store on another filesystem needs a
  # ReadWritePaths line -- and an update that silently replaced it would break
  # the host it was meant to improve. The drop-in below is why that edit is
  # usually unnecessary now, but an existing one is still theirs.
  fetch wintermute-node.service "$TMP/wintermute-node.service"
  if cmp -s "$TMP/wintermute-node.service" "$UNIT"; then
    say "    unit is current"
  else
    cp "$TMP/wintermute-node.service" "$UNIT.new"
    say "    $UNIT differs from the one shipped; left as it is"
    echo "    the new one is at $UNIT.new -- diff them if the agent misbehaves" >&2
  fi
else
  fetch wintermute-node.service "$UNIT"
  chmod 644 "$UNIT"
  say "    installed $UNIT"
fi

# A model store outside the state directory is unreachable under
# ProtectSystem=strict, and the symptom is permission denied on a directory that
# is plainly writable from a shell. A drop-in grants exactly that path, which
# beats asking an operator to edit a unit they did not write.
if [ -n "$STORE" ] && [ "${STORE#"$STATE_DIR"}" = "$STORE" ]; then
  mkdir -p "$DROPIN_DIR"
  {
    echo "# Written by the Wintermute node installer: the model store lives"
    echo "# outside StateDirectory, and ProtectSystem=strict hides it otherwise."
    echo "[Service]"
    echo "ReadWritePaths=$STORE"
  } > "$DROPIN_DIR/store.conf"
  mkdir -p "$STORE"
  chown "$SERVICE_USER":"$SERVICE_USER" "$STORE" 2>/dev/null || true
  say "    granted write access to $STORE"
fi

systemctl daemon-reload
if systemctl is-enabled --quiet wintermute-node 2>/dev/null; then
  systemctl restart wintermute-node
  say "Restarted wintermute-node"
else
  systemctl enable --now wintermute-node
  say "Started wintermute-node"
fi

echo
echo "Done. This host now reports to $SERVER."
echo
echo "  systemctl status wintermute-node     is it running"
echo "  journalctl -u wintermute-node -f     what it is saying"
echo
echo "On the server, add this machine's name to the backend that serves models"
echo "here, so fit verdicts are computed against this hardware:"
echo
echo '  { "name": "...", "kind": "llamacpp", "base_url": "...", "node": "<this node name>" }'
`
